//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Feed
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Введите страну")]
        [Display(Name = "Страна")]
        public string Name { get; set; }
        public string ShortDesc { get; set; }

        [Required(ErrorMessage = "Введите ваш комментарий")]
        [Display(Name = "Комментарий")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Введите ваше имя")]
        [Display(Name = "Имя")]
        public string Author { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
