//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourEntities1 : DbContext
    {
        public TourEntities1()
            : base("name=TourEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Feed> Feed { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<HotTours> HotTours { get; set; }
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<Placement> Placement { get; set; }
        public virtual DbSet<Reservation> Reservation { get; set; }
        public virtual DbSet<Resort> Resort { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
    }
}
