//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourEntities : DbContext
    {
        public TourEntities()
            : base("name=TourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Airticket> Airticket { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Fishing> Fishing { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<HotTours> HotTours { get; set; }
        public virtual DbSet<Placement> Placement { get; set; }
        public virtual DbSet<Resort> Resort { get; set; }
        public virtual DbSet<Sertificate> Sertificate { get; set; }
        public virtual DbSet<Studying> Studying { get; set; }
        public virtual DbSet<Visa> Visa { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
    }
}
