//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public Nullable<int> ReservationNumber { get; set; }
        public Nullable<int> Period { get; set; }
        public string DepartureDay { get; set; }
        public string FirstName { get; set; }
        public string Price { get; set; }
        public string Food { get; set; }
        public string TourType { get; set; }
        public string Location { get; set; }
        public Nullable<int> HotTourId { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Children { get; set; }
        public string HotelCategory { get; set; }
        public string Country { get; set; }
        public string PastPlace { get; set; }
        public string Finance { get; set; }
        public string Comment { get; set; }
    
        public virtual HotTours HotTours { get; set; }
        public virtual Reservation Reservation1 { get; set; }
        public virtual Reservation Reservation2 { get; set; }
    }
}
