//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resort
    {
        public Resort()
        {
            this.Hotel = new HashSet<Hotel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryId { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Hotel> Hotel { get; set; }
    }
}
